### ISSUE TITLE
Support von Multi-Profile

### ISSUE THREAD

**Issue by dpomt** [DigitalerSchulhof/iOS#2]
für Eltern wäre es klasse, wenn in der App mehrere Profile hinterlegt werden kann. Sonst muss man als Eltern entweder alle Kinder nach Infos fragen oder sich nacheinander für jedes Kind anmelden.

**Comment by jeengbe** [comment]
Dafür sind Elternaccounts vorgesehen. 
DigitalerSchulhof/Website#1
